### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by XingFen-Xie** [czh-98/STAR#3]
Thank you for sharing.When I run the training code, I get the problem.CUDA out of memory.What should I do to solve this problem. Thanks.`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 39.59 GiB total capacity; 37.29 GiB already allocated; 206.19 MiB free; 37.52 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

**Comment by czh-98** [comment]
GPU with more than 40GB is required to train our model :).
