### ISSUE TITLE
Exporting skeleton motion only

### ISSUE THREAD

**Issue by julkaztwittera** [czh-98/STAR#4]
Hi,
great work! I'm really impressed.

I wonder what is the fastest way to export the retargeted skeleton motion only, without the mesh?

**Comment by czh-98** [comment]
You may use blender [API](https://docs.blender.org/api/current/bpy.ops.export_scene.html), or convert fbx file to bvh file, to export skeleton only.

**Comment by julkaztwittera** [comment]
What if I wanted to export the motion as numpy file, but in Openpose format?

**Comment by czh-98** [comment]
> What if I wanted to export the motion as numpy file, but in Openpose format?

You may refer to the [correspondence](https://github.com/Meshcapade/wiki/blob/main/assets/SMPLX_OpenPose_mapping/README.md) between SMPLX and Openpose to export the desired file(s).
